[0m20:43:26.346272 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44c06c2d20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44c1677980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44c06c17c0>]}


============================== 20:43:26.361844 | ed565bac-b393-410b-91c4-154ad2550f58 ==============================
[0m20:43:26.361844 [info ] [MainThread]: Running with dbt=1.9.0
[0m20:43:26.364928 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root', 'debug': 'False', 'version_check': 'True', 'log_path': '/dbt/logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --profiles-dir /root --project-dir /dbt', 'send_anonymous_usage_stats': 'True'}
[0m20:43:26.382245 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'default'
[0m20:43:26.387526 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.19325364, "process_in_blocks": "0", "process_kernel_time": 0.506226, "process_mem_max_rss": "87528", "process_out_blocks": "1464", "process_user_time": 3.963845}
[0m20:43:26.389481 [debug] [MainThread]: Command `dbt run` failed at 20:43:26.389259 after 0.20 seconds
[0m20:43:26.390854 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44c0721760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44c06c2d20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f44c0194080>]}
[0m20:43:26.392130 [debug] [MainThread]: Flushing usage events
[0m20:43:26.871786 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:52:25.356112 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1244c0bcb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f124609c470>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1244630710>]}


============================== 20:52:25.366299 | ada1fa34-c36e-4759-9c22-d6ec4af1ef89 ==============================
[0m20:52:25.366299 [info ] [MainThread]: Running with dbt=1.9.0
[0m20:52:25.368853 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': '/dbt/logs', 'fail_fast': 'False', 'profiles_dir': '/root', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --profiles-dir /root --project-dir /dbt', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:52:25.378316 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'default'
[0m20:52:25.381447 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.111868426, "process_in_blocks": "0", "process_kernel_time": 0.23925, "process_mem_max_rss": "87332", "process_out_blocks": "1464", "process_user_time": 2.114976}
[0m20:52:25.382884 [debug] [MainThread]: Command `dbt run` failed at 20:52:25.382720 after 0.11 seconds
[0m20:52:25.383967 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1245af19d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f12443763c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f124485e480>]}
[0m20:52:25.385056 [debug] [MainThread]: Flushing usage events
[0m20:52:25.763234 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:02:05.153479 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fee86a17860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fee86b23380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fee885ee0c0>]}


============================== 21:02:05.163111 | a99d660c-524a-4bfd-8a16-313934b172aa ==============================
[0m21:02:05.163111 [info ] [MainThread]: Running with dbt=1.9.0
[0m21:02:05.165485 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': '/dbt/logs', 'fail_fast': 'False', 'profiles_dir': '/root', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run --profiles-dir /root --project-dir /dbt', 'send_anonymous_usage_stats': 'True'}
[0m21:02:05.176339 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'default'
[0m21:02:05.178527 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.109386384, "process_in_blocks": "0", "process_kernel_time": 0.237995, "process_mem_max_rss": "87396", "process_out_blocks": "1464", "process_user_time": 1.884926}
[0m21:02:05.180049 [debug] [MainThread]: Command `dbt run` failed at 21:02:05.179899 after 0.11 seconds
[0m21:02:05.181187 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fee89efea50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fee87101b20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fee86777e30>]}
[0m21:02:05.182268 [debug] [MainThread]: Flushing usage events
[0m21:02:05.494340 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:08:39.595605 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcc3b2dbe30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcc3aa42690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcc3a815220>]}


============================== 21:08:39.604585 | 52b18888-96f5-4086-9ed2-883f51b09bed ==============================
[0m21:08:39.604585 [info ] [MainThread]: Running with dbt=1.9.0
[0m21:08:39.606733 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root', 'debug': 'False', 'version_check': 'True', 'log_path': '/dbt/logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --profiles-dir /root --project-dir /dbt', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m21:08:39.908113 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '52b18888-96f5-4086-9ed2-883f51b09bed', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcc3af1bb00>]}
[0m21:08:40.022245 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '52b18888-96f5-4086-9ed2-883f51b09bed', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcc3a533140>]}
[0m21:08:40.025344 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m21:08:40.146977 [debug] [MainThread]: checksum: 568f1e1480817ea4790fb17980df195247d39d7f280a19e6fa3c1e276e1d1417, vars: {}, profile: custom_postgres, target: dev, version: 1.9.0
[0m21:08:40.152685 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m21:08:40.154355 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '52b18888-96f5-4086-9ed2-883f51b09bed', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcc3bf76330>]}
[0m21:08:41.966328 [error] [MainThread]: Encountered an error:
Parsing Error
  Invalid models config given in models/example/schema.yml @ models: {'name': 'actors', 'description': 'This table contains details about actors.', 'columns': [{'name': 'actor_id', 'description': 'Unique identifier of the actor.', 'tests': ['unique', 'not_null']}, {'name': 'name', 'description': 'First name of the actor.', 'tests': None}], 'original_file_path': 'models/example/schema.yml', 'yaml_key': 'models', 'package_name': 'custom_postgres'} - at path ['columns'][1]['tests']: None is not of type 'array'
[0m21:08:41.970293 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 2.4700313, "process_in_blocks": "0", "process_kernel_time": 0.233314, "process_mem_max_rss": "101944", "process_out_blocks": "1488", "process_user_time": 3.994336}
[0m21:08:41.973068 [debug] [MainThread]: Command `dbt run` failed at 21:08:41.972737 after 2.47 seconds
[0m21:08:41.974941 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcc3dd7ea20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcc38a797f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcc38b4a360>]}
[0m21:08:41.976517 [debug] [MainThread]: Flushing usage events
[0m21:08:42.291688 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:07:39.791306 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff8345c50a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff835c27650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff833c18cb0>]}


============================== 23:07:39.853981 | cf6180e8-675c-4223-8565-96797fd7a164 ==============================
[0m23:07:39.853981 [info ] [MainThread]: Running with dbt=1.9.0
[0m23:07:39.856058 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root', 'fail_fast': 'False', 'debug': 'False', 'log_path': '/dbt/logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --profiles-dir /root --project-dir /dbt', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:07:40.344369 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'cf6180e8-675c-4223-8565-96797fd7a164', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff833c7b560>]}
[0m23:07:40.487966 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'cf6180e8-675c-4223-8565-96797fd7a164', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff8339c3bc0>]}
[0m23:07:40.489946 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m23:07:40.654615 [debug] [MainThread]: checksum: 568f1e1480817ea4790fb17980df195247d39d7f280a19e6fa3c1e276e1d1417, vars: {}, profile: custom_postgres, target: dev, version: 1.9.0
[0m23:07:40.661196 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m23:07:40.662919 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'cf6180e8-675c-4223-8565-96797fd7a164', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff832111040>]}
[0m23:07:44.038059 [error] [MainThread]: Encountered an error:
Compilation Error
  Model 'model.custom_postgres.films' (models/example/films.sql) depends on a source named 'destination_db.films' which was not found
[0m23:07:44.041540 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 4.564001, "process_in_blocks": "0", "process_kernel_time": 0.538833, "process_mem_max_rss": "102488", "process_out_blocks": "1488", "process_user_time": 8.182284}
[0m23:07:44.044743 [debug] [MainThread]: Command `dbt run` failed at 23:07:44.044393 after 4.57 seconds
[0m23:07:44.047252 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff833a54170>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff831f3cc80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff831f89370>]}
[0m23:07:44.050658 [debug] [MainThread]: Flushing usage events
[0m23:07:44.347655 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:10:26.959516 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f121714d5b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f121714d610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f121714c2c0>]}


============================== 23:10:26.967806 | cf077a87-1a99-49b8-b4e6-78e006b9df38 ==============================
[0m23:10:26.967806 [info ] [MainThread]: Running with dbt=1.9.0
[0m23:10:26.970028 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/root', 'log_path': '/dbt/logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --profiles-dir /root --project-dir /dbt', 'send_anonymous_usage_stats': 'True'}
[0m23:10:26.983473 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'default'
[0m23:10:26.985920 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.11858111, "process_in_blocks": "0", "process_kernel_time": 0.16972, "process_mem_max_rss": "87356", "process_out_blocks": "1464", "process_user_time": 2.066592}
[0m23:10:26.987859 [debug] [MainThread]: Command `dbt run` failed at 23:10:26.987611 after 0.12 seconds
[0m23:10:26.989062 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f121710be60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f121714c530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f12178027b0>]}
[0m23:10:26.990222 [debug] [MainThread]: Flushing usage events
[0m23:10:27.461560 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:12:20.723086 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f20a7fd1c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f20a7cc0620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f20a7fd3a70>]}


============================== 23:12:20.730805 | fc5a641a-8397-442f-bff5-540086f1ad72 ==============================
[0m23:12:20.730805 [info ] [MainThread]: Running with dbt=1.9.0
[0m23:12:20.733105 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': '/dbt/logs', 'fail_fast': 'False', 'profiles_dir': '/root', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run --profiles-dir /root --project-dir /dbt', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m23:12:20.745174 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'default'
[0m23:12:20.747322 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.12905988, "process_in_blocks": "0", "process_kernel_time": 0.271367, "process_mem_max_rss": "87424", "process_out_blocks": "1464", "process_user_time": 1.799064}
[0m23:12:20.748939 [debug] [MainThread]: Command `dbt run` failed at 23:12:20.748718 after 0.13 seconds
[0m23:12:20.750203 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f20a86c8e00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f20a81dcfb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f20a7cc4770>]}
[0m23:12:20.751337 [debug] [MainThread]: Flushing usage events
[0m23:12:21.069133 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:14:04.702737 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb6abbb7ec0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb6abe189e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb6ac2fe7e0>]}


============================== 23:14:04.711165 | 79365ecc-932f-4678-8a4d-d872df9256d6 ==============================
[0m23:14:04.711165 [info ] [MainThread]: Running with dbt=1.9.0
[0m23:14:04.713274 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': '/dbt/logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run --profiles-dir /root --project-dir /dbt', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:14:04.991358 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '79365ecc-932f-4678-8a4d-d872df9256d6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb6abbb9220>]}
[0m23:14:05.073677 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '79365ecc-932f-4678-8a4d-d872df9256d6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb6aba6e810>]}
[0m23:14:05.076000 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m23:14:05.187794 [debug] [MainThread]: checksum: 568f1e1480817ea4790fb17980df195247d39d7f280a19e6fa3c1e276e1d1417, vars: {}, profile: custom_postgres, target: dev, version: 1.9.0
[0m23:14:05.194008 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m23:14:05.195852 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '79365ecc-932f-4678-8a4d-d872df9256d6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb6aa1653a0>]}
[0m23:14:07.078518 [error] [MainThread]: Encountered an error:
Compilation Error
  Model 'model.custom_postgres.films' (models/example/films.sql) depends on a source named 'destination_db.films' which was not found
[0m23:14:07.082254 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 2.4665256, "process_in_blocks": "48", "process_kernel_time": 0.346857, "process_mem_max_rss": "102744", "process_out_blocks": "1488", "process_user_time": 4.122651}
[0m23:14:07.084758 [debug] [MainThread]: Command `dbt run` failed at 23:14:07.084453 after 2.47 seconds
[0m23:14:07.086334 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb6abd003e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb6ab91b5c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb6a9cfe270>]}
[0m23:14:07.087809 [debug] [MainThread]: Flushing usage events
[0m23:14:07.326857 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:26:19.047708 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6894ca6480>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f68930c0680>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6894c142c0>]}


============================== 23:26:19.056785 | 464b6cba-8a2f-49a2-a4d5-ddd5bfab1986 ==============================
[0m23:26:19.056785 [info ] [MainThread]: Running with dbt=1.9.0
[0m23:26:19.058535 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root', 'version_check': 'True', 'fail_fast': 'False', 'log_path': '/dbt/logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run --profiles-dir /root --project-dir /dbt', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:26:19.070301 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'default'
[0m23:26:19.072636 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.11421077, "process_in_blocks": "82080", "process_kernel_time": 0.348654, "process_mem_max_rss": "86816", "process_out_blocks": "1464", "process_user_time": 1.966024}
[0m23:26:19.073842 [debug] [MainThread]: Command `dbt run` failed at 23:26:19.073691 after 0.12 seconds
[0m23:26:19.074862 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f689373cc20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6892f33770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6893820fb0>]}
[0m23:26:19.075894 [debug] [MainThread]: Flushing usage events
[0m23:26:19.478803 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:27:11.075291 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f516a984620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f516a986030>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f516aac0980>]}


============================== 23:27:11.083251 | 631a6b29-30e2-4b02-bbb6-659ad6debd1b ==============================
[0m23:27:11.083251 [info ] [MainThread]: Running with dbt=1.9.0
[0m23:27:11.085247 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root', 'fail_fast': 'False', 'debug': 'False', 'log_path': '/dbt/logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --profiles-dir /root --project-dir /dbt', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:27:11.440847 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '631a6b29-30e2-4b02-bbb6-659ad6debd1b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5169326240>]}
[0m23:27:11.527250 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '631a6b29-30e2-4b02-bbb6-659ad6debd1b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f51672044d0>]}
[0m23:27:11.532799 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m23:27:11.665814 [debug] [MainThread]: checksum: 568f1e1480817ea4790fb17980df195247d39d7f280a19e6fa3c1e276e1d1417, vars: {}, profile: custom_postgres, target: dev, version: 1.9.0
[0m23:27:11.671180 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m23:27:11.673066 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '631a6b29-30e2-4b02-bbb6-659ad6debd1b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f51672b0800>]}
[0m23:27:13.869005 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '631a6b29-30e2-4b02-bbb6-659ad6debd1b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5166e35b20>]}
[0m23:27:14.181367 [debug] [MainThread]: Wrote artifact WritableManifest to /dbt/target/manifest.json
[0m23:27:14.190004 [debug] [MainThread]: Wrote artifact SemanticManifest to /dbt/target/semantic_manifest.json
[0m23:27:14.241860 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '631a6b29-30e2-4b02-bbb6-659ad6debd1b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5165dbd5e0>]}
[0m23:27:14.243482 [info ] [MainThread]: Found 4 models, 20 data tests, 3 sources, 429 macros
[0m23:27:14.245366 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '631a6b29-30e2-4b02-bbb6-659ad6debd1b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5165d73cb0>]}
[0m23:27:14.250231 [info ] [MainThread]: 
[0m23:27:14.251977 [info ] [MainThread]: Concurrency: 1 threads (target='dev')
[0m23:27:14.253609 [info ] [MainThread]: 
[0m23:27:14.255745 [debug] [MainThread]: Acquiring new postgres connection 'master'
[0m23:27:14.264095 [debug] [ThreadPool]: Acquiring new postgres connection 'list_destination_db'
[0m23:27:14.328383 [debug] [ThreadPool]: Using postgres connection "list_destination_db"
[0m23:27:14.330184 [debug] [ThreadPool]: On list_destination_db: /* {"app": "dbt", "dbt_version": "1.9.0", "profile_name": "custom_postgres", "target_name": "dev", "connection_name": "list_destination_db"} */

    select distinct nspname from pg_namespace
  
[0m23:27:14.331537 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m23:27:14.413915 [debug] [ThreadPool]: SQL status: SELECT 4 in 0.082 seconds
[0m23:27:14.416555 [debug] [ThreadPool]: On list_destination_db: Close
[0m23:27:14.419408 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_destination_db, now list_destination_db_public)
[0m23:27:14.437705 [debug] [ThreadPool]: Using postgres connection "list_destination_db_public"
[0m23:27:14.439424 [debug] [ThreadPool]: On list_destination_db_public: BEGIN
[0m23:27:14.441145 [debug] [ThreadPool]: Opening a new connection, currently in state closed
[0m23:27:14.473016 [debug] [ThreadPool]: SQL status: BEGIN in 0.032 seconds
[0m23:27:14.474660 [debug] [ThreadPool]: Using postgres connection "list_destination_db_public"
[0m23:27:14.476420 [debug] [ThreadPool]: On list_destination_db_public: /* {"app": "dbt", "dbt_version": "1.9.0", "profile_name": "custom_postgres", "target_name": "dev", "connection_name": "list_destination_db_public"} */
select
      'destination_db' as database,
      tablename as name,
      schemaname as schema,
      'table' as type
    from pg_tables
    where schemaname ilike 'public'
    union all
    select
      'destination_db' as database,
      viewname as name,
      schemaname as schema,
      'view' as type
    from pg_views
    where schemaname ilike 'public'
    union all
    select
      'destination_db' as database,
      matviewname as name,
      schemaname as schema,
      'materialized_view' as type
    from pg_matviews
    where schemaname ilike 'public'
  
[0m23:27:14.487043 [debug] [ThreadPool]: SQL status: SELECT 5 in 0.009 seconds
[0m23:27:14.490575 [debug] [ThreadPool]: On list_destination_db_public: ROLLBACK
[0m23:27:14.493577 [debug] [ThreadPool]: On list_destination_db_public: Close
[0m23:27:14.503911 [debug] [MainThread]: Using postgres connection "master"
[0m23:27:14.505135 [debug] [MainThread]: On master: BEGIN
[0m23:27:14.506149 [debug] [MainThread]: Opening a new connection, currently in state init
[0m23:27:14.529351 [debug] [MainThread]: SQL status: BEGIN in 0.023 seconds
[0m23:27:14.531267 [debug] [MainThread]: Using postgres connection "master"
[0m23:27:14.533074 [debug] [MainThread]: On master: /* {"app": "dbt", "dbt_version": "1.9.0", "profile_name": "custom_postgres", "target_name": "dev", "connection_name": "master"} */
with relation as (
        select
            pg_rewrite.ev_class as class,
            pg_rewrite.oid as id
        from pg_rewrite
    ),
    class as (
        select
            oid as id,
            relname as name,
            relnamespace as schema,
            relkind as kind
        from pg_class
    ),
    dependency as (
        select distinct
            pg_depend.objid as id,
            pg_depend.refobjid as ref
        from pg_depend
    ),
    schema as (
        select
            pg_namespace.oid as id,
            pg_namespace.nspname as name
        from pg_namespace
        where nspname != 'information_schema' and nspname not like 'pg\_%'
    ),
    referenced as (
        select
            relation.id AS id,
            referenced_class.name ,
            referenced_class.schema ,
            referenced_class.kind
        from relation
        join class as referenced_class on relation.class=referenced_class.id
        where referenced_class.kind in ('r', 'v', 'm')
    ),
    relationships as (
        select
            referenced.name as referenced_name,
            referenced.schema as referenced_schema_id,
            dependent_class.name as dependent_name,
            dependent_class.schema as dependent_schema_id,
            referenced.kind as kind
        from referenced
        join dependency on referenced.id=dependency.id
        join class as dependent_class on dependency.ref=dependent_class.id
        where
            (referenced.name != dependent_class.name or
             referenced.schema != dependent_class.schema)
    )

    select
        referenced_schema.name as referenced_schema,
        relationships.referenced_name as referenced_name,
        dependent_schema.name as dependent_schema,
        relationships.dependent_name as dependent_name
    from relationships
    join schema as dependent_schema on relationships.dependent_schema_id=dependent_schema.id
    join schema as referenced_schema on relationships.referenced_schema_id=referenced_schema.id
    group by referenced_schema, referenced_name, dependent_schema, dependent_name
    order by referenced_schema, referenced_name, dependent_schema, dependent_name;
[0m23:27:14.540524 [debug] [MainThread]: SQL status: SELECT 0 in 0.005 seconds
[0m23:27:14.543457 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '631a6b29-30e2-4b02-bbb6-659ad6debd1b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f51650dd010>]}
[0m23:27:14.545018 [debug] [MainThread]: On master: ROLLBACK
[0m23:27:14.548146 [debug] [MainThread]: Using postgres connection "master"
[0m23:27:14.549768 [debug] [MainThread]: On master: BEGIN
[0m23:27:14.554942 [debug] [MainThread]: SQL status: BEGIN in 0.004 seconds
[0m23:27:14.556560 [debug] [MainThread]: On master: COMMIT
[0m23:27:14.558257 [debug] [MainThread]: Using postgres connection "master"
[0m23:27:14.559900 [debug] [MainThread]: On master: COMMIT
[0m23:27:14.563435 [debug] [MainThread]: SQL status: COMMIT in 0.002 seconds
[0m23:27:14.565098 [debug] [MainThread]: On master: Close
[0m23:27:14.569604 [debug] [Thread-1 (]: Began running node model.custom_postgres.actors
[0m23:27:14.571883 [info ] [Thread-1 (]: 1 of 4 START sql table model public.actors ..................................... [RUN]
[0m23:27:14.573759 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly list_destination_db_public, now model.custom_postgres.actors)
[0m23:27:14.575677 [debug] [Thread-1 (]: Began compiling node model.custom_postgres.actors
[0m23:27:14.597203 [debug] [Thread-1 (]: Writing injected SQL for node "model.custom_postgres.actors"
[0m23:27:14.619427 [debug] [Thread-1 (]: Began executing node model.custom_postgres.actors
[0m23:27:14.702894 [debug] [Thread-1 (]: Writing runtime sql for node "model.custom_postgres.actors"
[0m23:27:14.720376 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.actors"
[0m23:27:14.721731 [debug] [Thread-1 (]: On model.custom_postgres.actors: BEGIN
[0m23:27:14.722976 [debug] [Thread-1 (]: Opening a new connection, currently in state closed
[0m23:27:14.743099 [debug] [Thread-1 (]: SQL status: BEGIN in 0.020 seconds
[0m23:27:14.744577 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.actors"
[0m23:27:14.745666 [debug] [Thread-1 (]: On model.custom_postgres.actors: /* {"app": "dbt", "dbt_version": "1.9.0", "profile_name": "custom_postgres", "target_name": "dev", "node_id": "model.custom_postgres.actors"} */

  
    

  create  table "destination_db"."public"."actors__dbt_tmp"
  
  
    as
  
  (
    SELECT * FROM "destination_db"."public"."actors"
  );
  
[0m23:27:14.749340 [debug] [Thread-1 (]: SQL status: SELECT 20 in 0.003 seconds
[0m23:27:14.759517 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.actors"
[0m23:27:14.760636 [debug] [Thread-1 (]: On model.custom_postgres.actors: /* {"app": "dbt", "dbt_version": "1.9.0", "profile_name": "custom_postgres", "target_name": "dev", "node_id": "model.custom_postgres.actors"} */
alter table "destination_db"."public"."actors" rename to "actors__dbt_backup"
[0m23:27:14.763405 [debug] [Thread-1 (]: SQL status: ALTER TABLE in 0.002 seconds
[0m23:27:14.768302 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.actors"
[0m23:27:14.769651 [debug] [Thread-1 (]: On model.custom_postgres.actors: /* {"app": "dbt", "dbt_version": "1.9.0", "profile_name": "custom_postgres", "target_name": "dev", "node_id": "model.custom_postgres.actors"} */
alter table "destination_db"."public"."actors__dbt_tmp" rename to "actors"
[0m23:27:14.772331 [debug] [Thread-1 (]: SQL status: ALTER TABLE in 0.001 seconds
[0m23:27:14.803054 [debug] [Thread-1 (]: On model.custom_postgres.actors: COMMIT
[0m23:27:14.804269 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.actors"
[0m23:27:14.805304 [debug] [Thread-1 (]: On model.custom_postgres.actors: COMMIT
[0m23:27:14.812002 [debug] [Thread-1 (]: SQL status: COMMIT in 0.006 seconds
[0m23:27:14.821796 [debug] [Thread-1 (]: Applying DROP to: "destination_db"."public"."actors__dbt_backup"
[0m23:27:14.830810 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.actors"
[0m23:27:14.832330 [debug] [Thread-1 (]: On model.custom_postgres.actors: /* {"app": "dbt", "dbt_version": "1.9.0", "profile_name": "custom_postgres", "target_name": "dev", "node_id": "model.custom_postgres.actors"} */
drop table if exists "destination_db"."public"."actors__dbt_backup" cascade
[0m23:27:14.838813 [debug] [Thread-1 (]: SQL status: DROP TABLE in 0.005 seconds
[0m23:27:14.843423 [debug] [Thread-1 (]: On model.custom_postgres.actors: Close
[0m23:27:14.846862 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '631a6b29-30e2-4b02-bbb6-659ad6debd1b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f516aa42900>]}
[0m23:27:14.848645 [info ] [Thread-1 (]: 1 of 4 OK created sql table model public.actors ................................ [[32mSELECT 20[0m in 0.27s]
[0m23:27:14.850928 [debug] [Thread-1 (]: Finished running node model.custom_postgres.actors
[0m23:27:14.852620 [debug] [Thread-1 (]: Began running node model.custom_postgres.film_actors
[0m23:27:14.854498 [info ] [Thread-1 (]: 2 of 4 START sql table model public.film_actors ................................ [RUN]
[0m23:27:14.856465 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly model.custom_postgres.actors, now model.custom_postgres.film_actors)
[0m23:27:14.858248 [debug] [Thread-1 (]: Began compiling node model.custom_postgres.film_actors
[0m23:27:14.863393 [debug] [Thread-1 (]: Writing injected SQL for node "model.custom_postgres.film_actors"
[0m23:27:14.871852 [debug] [Thread-1 (]: Began executing node model.custom_postgres.film_actors
[0m23:27:14.879829 [debug] [Thread-1 (]: Writing runtime sql for node "model.custom_postgres.film_actors"
[0m23:27:14.887660 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.film_actors"
[0m23:27:14.888779 [debug] [Thread-1 (]: On model.custom_postgres.film_actors: BEGIN
[0m23:27:14.889758 [debug] [Thread-1 (]: Opening a new connection, currently in state closed
[0m23:27:14.911983 [debug] [Thread-1 (]: SQL status: BEGIN in 0.022 seconds
[0m23:27:14.913544 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.film_actors"
[0m23:27:14.914889 [debug] [Thread-1 (]: On model.custom_postgres.film_actors: /* {"app": "dbt", "dbt_version": "1.9.0", "profile_name": "custom_postgres", "target_name": "dev", "node_id": "model.custom_postgres.film_actors"} */

  
    

  create  table "destination_db"."public"."film_actors__dbt_tmp"
  
  
    as
  
  (
    SELECT * FROM "destination_db"."public"."film_actors"
  );
  
[0m23:27:14.919211 [debug] [Thread-1 (]: SQL status: SELECT 20 in 0.003 seconds
[0m23:27:14.925510 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.film_actors"
[0m23:27:14.926701 [debug] [Thread-1 (]: On model.custom_postgres.film_actors: /* {"app": "dbt", "dbt_version": "1.9.0", "profile_name": "custom_postgres", "target_name": "dev", "node_id": "model.custom_postgres.film_actors"} */
alter table "destination_db"."public"."film_actors" rename to "film_actors__dbt_backup"
[0m23:27:14.929322 [debug] [Thread-1 (]: SQL status: ALTER TABLE in 0.002 seconds
[0m23:27:14.933930 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.film_actors"
[0m23:27:14.935097 [debug] [Thread-1 (]: On model.custom_postgres.film_actors: /* {"app": "dbt", "dbt_version": "1.9.0", "profile_name": "custom_postgres", "target_name": "dev", "node_id": "model.custom_postgres.film_actors"} */
alter table "destination_db"."public"."film_actors__dbt_tmp" rename to "film_actors"
[0m23:27:14.938126 [debug] [Thread-1 (]: SQL status: ALTER TABLE in 0.002 seconds
[0m23:27:14.941692 [debug] [Thread-1 (]: On model.custom_postgres.film_actors: COMMIT
[0m23:27:14.942932 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.film_actors"
[0m23:27:14.943988 [debug] [Thread-1 (]: On model.custom_postgres.film_actors: COMMIT
[0m23:27:14.948181 [debug] [Thread-1 (]: SQL status: COMMIT in 0.003 seconds
[0m23:27:14.953440 [debug] [Thread-1 (]: Applying DROP to: "destination_db"."public"."film_actors__dbt_backup"
[0m23:27:14.955745 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.film_actors"
[0m23:27:14.957128 [debug] [Thread-1 (]: On model.custom_postgres.film_actors: /* {"app": "dbt", "dbt_version": "1.9.0", "profile_name": "custom_postgres", "target_name": "dev", "node_id": "model.custom_postgres.film_actors"} */
drop table if exists "destination_db"."public"."film_actors__dbt_backup" cascade
[0m23:27:14.962161 [debug] [Thread-1 (]: SQL status: DROP TABLE in 0.004 seconds
[0m23:27:14.964844 [debug] [Thread-1 (]: On model.custom_postgres.film_actors: Close
[0m23:27:14.966321 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '631a6b29-30e2-4b02-bbb6-659ad6debd1b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5164f80500>]}
[0m23:27:14.968189 [info ] [Thread-1 (]: 2 of 4 OK created sql table model public.film_actors ........................... [[32mSELECT 20[0m in 0.11s]
[0m23:27:14.970334 [debug] [Thread-1 (]: Finished running node model.custom_postgres.film_actors
[0m23:27:14.972152 [debug] [Thread-1 (]: Began running node model.custom_postgres.films
[0m23:27:14.973943 [info ] [Thread-1 (]: 3 of 4 START sql table model public.films ...................................... [RUN]
[0m23:27:14.975635 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly model.custom_postgres.film_actors, now model.custom_postgres.films)
[0m23:27:14.976982 [debug] [Thread-1 (]: Began compiling node model.custom_postgres.films
[0m23:27:14.982191 [debug] [Thread-1 (]: Writing injected SQL for node "model.custom_postgres.films"
[0m23:27:14.990220 [debug] [Thread-1 (]: Began executing node model.custom_postgres.films
[0m23:27:14.996106 [debug] [Thread-1 (]: Writing runtime sql for node "model.custom_postgres.films"
[0m23:27:15.004989 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.films"
[0m23:27:15.006131 [debug] [Thread-1 (]: On model.custom_postgres.films: BEGIN
[0m23:27:15.007217 [debug] [Thread-1 (]: Opening a new connection, currently in state closed
[0m23:27:15.030615 [debug] [Thread-1 (]: SQL status: BEGIN in 0.023 seconds
[0m23:27:15.031886 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.films"
[0m23:27:15.032993 [debug] [Thread-1 (]: On model.custom_postgres.films: /* {"app": "dbt", "dbt_version": "1.9.0", "profile_name": "custom_postgres", "target_name": "dev", "node_id": "model.custom_postgres.films"} */

  
    

  create  table "destination_db"."public"."films__dbt_tmp"
  
  
    as
  
  (
    SELECT * FROM "destination_db"."public"."films"
  );
  
[0m23:27:15.036874 [debug] [Thread-1 (]: SQL status: SELECT 20 in 0.003 seconds
[0m23:27:15.042543 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.films"
[0m23:27:15.043665 [debug] [Thread-1 (]: On model.custom_postgres.films: /* {"app": "dbt", "dbt_version": "1.9.0", "profile_name": "custom_postgres", "target_name": "dev", "node_id": "model.custom_postgres.films"} */
alter table "destination_db"."public"."films" rename to "films__dbt_backup"
[0m23:27:15.046262 [debug] [Thread-1 (]: SQL status: ALTER TABLE in 0.001 seconds
[0m23:27:15.051616 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.films"
[0m23:27:15.052742 [debug] [Thread-1 (]: On model.custom_postgres.films: /* {"app": "dbt", "dbt_version": "1.9.0", "profile_name": "custom_postgres", "target_name": "dev", "node_id": "model.custom_postgres.films"} */
alter table "destination_db"."public"."films__dbt_tmp" rename to "films"
[0m23:27:15.055445 [debug] [Thread-1 (]: SQL status: ALTER TABLE in 0.002 seconds
[0m23:27:15.058312 [debug] [Thread-1 (]: On model.custom_postgres.films: COMMIT
[0m23:27:15.059389 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.films"
[0m23:27:15.060363 [debug] [Thread-1 (]: On model.custom_postgres.films: COMMIT
[0m23:27:15.064349 [debug] [Thread-1 (]: SQL status: COMMIT in 0.003 seconds
[0m23:27:15.068665 [debug] [Thread-1 (]: Applying DROP to: "destination_db"."public"."films__dbt_backup"
[0m23:27:15.070469 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.films"
[0m23:27:15.071744 [debug] [Thread-1 (]: On model.custom_postgres.films: /* {"app": "dbt", "dbt_version": "1.9.0", "profile_name": "custom_postgres", "target_name": "dev", "node_id": "model.custom_postgres.films"} */
drop table if exists "destination_db"."public"."films__dbt_backup" cascade
[0m23:27:15.077695 [debug] [Thread-1 (]: SQL status: DROP TABLE in 0.005 seconds
[0m23:27:15.080142 [debug] [Thread-1 (]: On model.custom_postgres.films: Close
[0m23:27:15.081588 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '631a6b29-30e2-4b02-bbb6-659ad6debd1b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5164f7a2a0>]}
[0m23:27:15.083316 [info ] [Thread-1 (]: 3 of 4 OK created sql table model public.films ................................. [[32mSELECT 20[0m in 0.11s]
[0m23:27:15.085581 [debug] [Thread-1 (]: Finished running node model.custom_postgres.films
[0m23:27:15.087791 [debug] [Thread-1 (]: Began running node model.custom_postgres.film_ratings
[0m23:27:15.088966 [info ] [Thread-1 (]: 4 of 4 START sql table model public.film_ratings ............................... [RUN]
[0m23:27:15.090289 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly model.custom_postgres.films, now model.custom_postgres.film_ratings)
[0m23:27:15.091304 [debug] [Thread-1 (]: Began compiling node model.custom_postgres.film_ratings
[0m23:27:15.098543 [debug] [Thread-1 (]: Writing injected SQL for node "model.custom_postgres.film_ratings"
[0m23:27:15.106408 [debug] [Thread-1 (]: Began executing node model.custom_postgres.film_ratings
[0m23:27:15.112831 [debug] [Thread-1 (]: Writing runtime sql for node "model.custom_postgres.film_ratings"
[0m23:27:15.120530 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.film_ratings"
[0m23:27:15.121646 [debug] [Thread-1 (]: On model.custom_postgres.film_ratings: BEGIN
[0m23:27:15.122695 [debug] [Thread-1 (]: Opening a new connection, currently in state closed
[0m23:27:15.145658 [debug] [Thread-1 (]: SQL status: BEGIN in 0.023 seconds
[0m23:27:15.146787 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.film_ratings"
[0m23:27:15.147916 [debug] [Thread-1 (]: On model.custom_postgres.film_ratings: /* {"app": "dbt", "dbt_version": "1.9.0", "profile_name": "custom_postgres", "target_name": "dev", "node_id": "model.custom_postgres.film_ratings"} */

  
    

  create  table "destination_db"."public"."film_ratings__dbt_tmp"
  
  
    as
  
  (
    WITH films_with_ratings AS (
    SELECT 
        film_id,
        title,
        release_date,
        price,
        rating,
        user_rating,
        CASE
            WHEN user_rating >= 4.5 THEN 'Excellent'
            WHEN user_rating >= 4.0 THEN 'Good'
            WHEN user_rating >= 3.0 THEN 'Average'
            ELSE 'Poor'
        END as rating_category
    FROM "destination_db"."public"."films"
),

films_with_actors AS (
    SELECT
        f.film_id,
        f.title,
        STRING_AGG(a.actor_name, ',') AS actors
    FROM "destination_db"."public"."films" f
    LEFT JOIN "destination_db"."public"."film_actors" fa ON f.film_id = fa.film_id
    LEFT JOIN "destination_db"."public"."actors" a ON fa.actor_id = a.actor_id
    GROUP BY f.film_id, f.title
)

SELECT 
    fwf.*,
    fwa.actors
FROM films_with_ratings fwf
LEFT JOIN films_with_actors fwa ON fwf.film_id = fwa.film_id
  );
  
[0m23:27:15.153740 [debug] [Thread-1 (]: SQL status: SELECT 20 in 0.004 seconds
[0m23:27:15.158754 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.film_ratings"
[0m23:27:15.159980 [debug] [Thread-1 (]: On model.custom_postgres.film_ratings: /* {"app": "dbt", "dbt_version": "1.9.0", "profile_name": "custom_postgres", "target_name": "dev", "node_id": "model.custom_postgres.film_ratings"} */
alter table "destination_db"."public"."film_ratings__dbt_tmp" rename to "film_ratings"
[0m23:27:15.162597 [debug] [Thread-1 (]: SQL status: ALTER TABLE in 0.002 seconds
[0m23:27:15.165909 [debug] [Thread-1 (]: On model.custom_postgres.film_ratings: COMMIT
[0m23:27:15.167254 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.film_ratings"
[0m23:27:15.168332 [debug] [Thread-1 (]: On model.custom_postgres.film_ratings: COMMIT
[0m23:27:15.173134 [debug] [Thread-1 (]: SQL status: COMMIT in 0.003 seconds
[0m23:27:15.178542 [debug] [Thread-1 (]: Applying DROP to: "destination_db"."public"."film_ratings__dbt_backup"
[0m23:27:15.179972 [debug] [Thread-1 (]: Using postgres connection "model.custom_postgres.film_ratings"
[0m23:27:15.180954 [debug] [Thread-1 (]: On model.custom_postgres.film_ratings: /* {"app": "dbt", "dbt_version": "1.9.0", "profile_name": "custom_postgres", "target_name": "dev", "node_id": "model.custom_postgres.film_ratings"} */
drop table if exists "destination_db"."public"."film_ratings__dbt_backup" cascade
[0m23:27:15.184168 [debug] [Thread-1 (]: SQL status: DROP TABLE in 0.002 seconds
[0m23:27:15.186877 [debug] [Thread-1 (]: On model.custom_postgres.film_ratings: Close
[0m23:27:15.188538 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '631a6b29-30e2-4b02-bbb6-659ad6debd1b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5164fd6b10>]}
[0m23:27:15.190379 [info ] [Thread-1 (]: 4 of 4 OK created sql table model public.film_ratings .......................... [[32mSELECT 20[0m in 0.10s]
[0m23:27:15.192474 [debug] [Thread-1 (]: Finished running node model.custom_postgres.film_ratings
[0m23:27:15.195962 [debug] [MainThread]: Using postgres connection "master"
[0m23:27:15.197263 [debug] [MainThread]: On master: BEGIN
[0m23:27:15.198152 [debug] [MainThread]: Opening a new connection, currently in state closed
[0m23:27:15.216208 [debug] [MainThread]: SQL status: BEGIN in 0.018 seconds
[0m23:27:15.217668 [debug] [MainThread]: On master: COMMIT
[0m23:27:15.218727 [debug] [MainThread]: Using postgres connection "master"
[0m23:27:15.219979 [debug] [MainThread]: On master: COMMIT
[0m23:27:15.222273 [debug] [MainThread]: SQL status: COMMIT in 0.001 seconds
[0m23:27:15.223343 [debug] [MainThread]: On master: Close
[0m23:27:15.225302 [debug] [MainThread]: Connection 'master' was properly closed.
[0m23:27:15.226674 [debug] [MainThread]: Connection 'model.custom_postgres.film_ratings' was properly closed.
[0m23:27:15.227872 [info ] [MainThread]: 
[0m23:27:15.229480 [info ] [MainThread]: Finished running 4 table models in 0 hours 0 minutes and 0.97 seconds (0.97s).
[0m23:27:15.232319 [debug] [MainThread]: Command end result
[0m23:27:15.301765 [debug] [MainThread]: Wrote artifact WritableManifest to /dbt/target/manifest.json
[0m23:27:15.307302 [debug] [MainThread]: Wrote artifact SemanticManifest to /dbt/target/semantic_manifest.json
[0m23:27:15.321797 [debug] [MainThread]: Wrote artifact RunExecutionResult to /dbt/target/run_results.json
[0m23:27:15.322803 [info ] [MainThread]: 
[0m23:27:15.324259 [info ] [MainThread]: [32mCompleted successfully[0m
[0m23:27:15.325630 [info ] [MainThread]: 
[0m23:27:15.326937 [info ] [MainThread]: Done. PASS=4 WARN=0 ERROR=0 SKIP=0 TOTAL=4
[0m23:27:15.328919 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": true, "command_wall_clock_time": 4.3451986, "process_in_blocks": "19016", "process_kernel_time": 0.340548, "process_mem_max_rss": "113556", "process_out_blocks": "1600", "process_user_time": 5.490056}
[0m23:27:15.330183 [debug] [MainThread]: Command `dbt run` succeeded at 23:27:15.330018 after 4.35 seconds
[0m23:27:15.331196 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5168d4d010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5168d4d0a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f516a43d8e0>]}
[0m23:27:15.332161 [debug] [MainThread]: Flushing usage events
[0m23:27:15.622715 [debug] [MainThread]: An error was encountered while trying to flush usage events
